name: AUTOTEST

on:
  push:
    branches: 
      - test.md
 
jobs:
    pullrequest:
      runs-on: ubuntu-latest
      # if: contains(github.event.head_commit.message, 'Done')
      steps:
        - uses: actions/checkout@v2
          
        - name: pull-request
          uses: repo-sync/pull-request@v2
          with: 
            source_branch: ""
            destination_branch: "russian1"
            pr_title: "PR for update russian1"
            pr_body: ":crown: *An automated PR*"
            pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
            pr_reviewer: ""
            pr_assignee: "irivanych"
            pr_label: "auto-pr"
            pr_milestone: "Milestone 1"
            pr-draft: true
            github_token: ${{ secrets.GITHUB_TOKEN }}
        - name: Check outputs
          run: |
            echo "Pull Request Number"
